### ISSUE TITLE
Fish version?

### ISSUE THREAD

**Issue by joehillen** [NullSense/fuzzy-sys#4]
The README says how to install the fish version, but there aren't fish files in the repo. Want help writing a fish version?

**Comment by NullSense** [comment]
Oh yeah that's erroneous, thanks for pointing that out, feel free to contribute a fish version! @joehillen

**Comment by NullSense** [comment]
@joehillen are you still planning on picking this issue up?

**Comment by joehillen** [comment]
@NullSense I looked at this over the weekend, and it turns out that there is nothing ZSH specific about this script and I think it makes more sense as a standalone program than a shell function. While refactoring it as such, I found a lot other improvements I could make and it ended up being almost a complete rewrite. I changed the name to sysz because **fs**ys can be interpreted as something related to the filesystem.

Thank you for the inspiration! It's likely not perfect as I haven't used it very much yet. https://github.com/joehillen/sysz
